[default]
GATEWAY_API='API_KEY'
GATEWAY_CRYP='CRYP_KEY'
PAYMENT_GATEWAY_URL='URL_GATEWAY'
SENDGRID_API_KEY='API_KEY'
EMAIL_FROM = "EMAIL"
REDIS_URL="redis://:@localhost:6379"
REDIS_DB = 0
SETRY_DSN = "https://xxxx@yyyy.ingest.sentry.io/000"
STRIPE_API_KEY= "pk_test_xxxx"
STRIPE_SECRET_KEY = "sk_test_yyyy"
BROKER_URL = "amqp://guest:guest@localhost:5672//"
RESULT_BACKEND = "rpc://"
CORREIOSBR_USER = "xxxx"
CORREIOSBR_PASS = "yyyy"
CORREIOSBR_API_SECRET = "zzzz"

[development]
DATABASE_URL="postgresql://user:pass@host/database"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15

[testing]
DATABASE_URL="postgresql://postgres_user:pass123@localhost/ecommerce"
DATABASE_URL="postgresql://user:pass@host/database"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15
