"""fix relationship orders

Revision ID: 36bcc3103719
Revises: 90b63f031694
Create Date: 2020-07-08 20:55:09.494970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bcc3103719'
down_revision = '90b63f031694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoiceitems', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoiceitems', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoiceitems', type_='foreignkey')
    op.drop_column('invoiceitems', 'product_id')
    # ### end Alembic commands ###
