"""Change installments in product to list of arrays

Revision ID: 37b6d9445907
Revises: e3c7efafba59
Create Date: 2020-09-02 07:49:49.655353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37b6d9445907'
down_revision = 'e3c7efafba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('installments_list', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.drop_column('product', 'installments_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('installments_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product', 'installments_list')
    # ### end Alembic commands ###
