"""Create Adress Table

Revision ID: 4386ebc507da
Revises: 36bcc3103719
Create Date: 2020-07-14 18:43:03.613211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4386ebc507da'
down_revision = '36bcc3103719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=58), nullable=True),
    sa.Column('city', sa.String(length=58), nullable=True),
    sa.Column('state', sa.String(length=58), nullable=True),
    sa.Column('neighborhood', sa.String(length=58), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('street_number', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
