"""Generate Steps Order

Revision ID: 473fbcd8ead5
Revises: 88d286691531
Create Date: 2020-09-28 07:58:07.041184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473fbcd8ead5'
down_revision = '88d286691531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderstatussteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('sending', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoice', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('invoice', sa.Column('tracking_number', sa.Integer(), nullable=True))
    op.drop_column('invoice', 'invoice_items_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_items_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('invoice', 'tracking_number')
    op.drop_column('invoice', 'payment_id')
    op.drop_table('orderstatussteps')
    # ### end Alembic commands ###
