"""add gateway_id

Revision ID: 558effa87e2e
Revises: fbb5bca28974
Create Date: 2020-11-20 17:48:58.190668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "558effa87e2e"
down_revision = "fbb5bca28974"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment", sa.Column("gateway_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "gateway_id")
    # ### end Alembic commands ###
