"""Generate Order tables

Revision ID: 6a3704887b75
Revises: 473fbcd8ead5
Create Date: 2020-10-27 13:08:55.710457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a3704887b75'
down_revision = '473fbcd8ead5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invoice')
    op.drop_table('invoiceitems')
    op.add_column('transaction', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_column('transaction', 'invoice')
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.add_column('transaction', sa.Column('invoice', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'order_id')
    op.create_table('invoiceitems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='invoiceitems_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='invoiceitems_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoiceitems_pkey')
    )
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], name='invoice_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoice_pkey')
    )
    op.drop_table('orderitems')
    op.drop_table('order')
    # ### end Alembic commands ###
