"""add category

Revision ID: 766ac3a1776c
Revises: 4ed0b67518ec
Create Date: 2020-12-08 09:40:18.395146
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '766ac3a1776c'
down_revision = '4ed0b67518ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
