"""Add uri column in product

Revision ID: 773d7924682e
Revises: 0be6f109af98
Create Date: 2020-07-27 20:24:04.619422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773d7924682e'
down_revision = '0be6f109af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'uri')
    # ### end Alembic commands ###
