"""fix relationship orders

Revision ID: 7fe7297a8eee
Revises: c2364128db28
Create Date: 2020-07-08 20:14:45.625099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe7297a8eee'
down_revision = 'c2364128db28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
