"""fix relationship orders

Revision ID: 90b63f031694
Revises: 7fe7297a8eee
Create Date: 2020-07-08 20:15:09.825208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b63f031694'
down_revision = '7fe7297a8eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
