"""Add description and url_path in Product

Revision ID: b655f3d7af00
Revises: 773d7924682e
Create Date: 2020-08-05 20:51:01.533945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b655f3d7af00'
down_revision = '773d7924682e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=True))
    op.add_column('product', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
