"""Update Adress add complement and category

Revision ID: bbcc44db2d7a
Revises: 4386ebc507da
Create Date: 2020-07-14 20:15:50.438386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcc44db2d7a'
down_revision = '4386ebc507da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_complement', sa.String(), nullable=True))
    op.add_column('address', sa.Column('category', sa.String(), nullable=True))
    op.add_column('address', sa.Column('type_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'type_address')
    op.drop_column('address', 'category')
    op.drop_column('address', 'address_complement')
    # ### end Alembic commands ###
