"""fix relationship orders

Revision ID: c2364128db28
Revises: d1514aaf7471
Create Date: 2020-07-07 21:59:45.631059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2364128db28'
down_revision = 'd1514aaf7471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoiceitems', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoiceitems', 'invoice', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoiceitems', type_='foreignkey')
    op.drop_column('invoiceitems', 'invoice_id')
    # ### end Alembic commands ###
