"""fix relationship orders

Revision ID: d1514aaf7471
Revises: 0b116fe2c25b
Create Date: 2020-07-07 21:46:05.341651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1514aaf7471'
down_revision = '0b116fe2c25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'user', ['customer_id'], ['id'])
    op.add_column('product', sa.Column('direct_sales', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('upsell', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('product', 'invoice_items_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('invoice_items_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'upsell')
    op.drop_column('product', 'direct_sales')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'customer_id')
    # ### end Alembic commands ###
