"""create table user-reset-password

Revision ID: d9a7b005a2e9
Revises: 425e147e716b
Create Date: 2021-04-30 15:08:28.376462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a7b005a2e9'
down_revision = '425e147e716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userresetpassword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('used_token', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('product', 'heigth',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('product', 'weigth',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('product', 'width',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'width',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('product', 'weigth',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('product', 'heigth',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('userresetpassword')
    # ### end Alembic commands ###
