"""add new columns

Revision ID: e4dd5fb9b8ac
Revises: f839ce991ab7
Create Date: 2020-11-26 11:45:18.583785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4dd5fb9b8ac"
down_revision = "f839ce991ab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("depthe", sa.Integer(), nullable=True))
    op.add_column("product", sa.Column("heigth", sa.Integer(), nullable=True))
    op.add_column("product", sa.Column("weigth", sa.Integer(), nullable=True))
    op.add_column("product", sa.Column("width", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "width")
    op.drop_column("product", "weigth")
    op.drop_column("product", "heigth")
    op.drop_column("product", "depthe")
    # ### end Alembic commands ###
