"""add control fields in cupon table

Revision ID: edc233fe9449
Revises: dad47228ad42
Create Date: 2020-11-10 08:52:53.871899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edc233fe9449"
down_revision = "dad47228ad42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cupons", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("cupons", sa.Column("qty", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cupons", "qty")
    op.drop_column("cupons", "active")
    # ### end Alembic commands ###
