services:


  postgres:
    image: "postgres:14.8"
    container_name: ecommercedb
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - pg14:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379


volumes:
  pg14:
  redis-v:

