"""add customer table

Revision ID: 0258cb1bef06
Revises: ee0f2b9481ba
Create Date: 2023-09-21 09:02:02.540452
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0258cb1bef06'
down_revision: Union[str, None] = 'ee0f2b9481ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customer',
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('customer_uuid', sa.String(), nullable=False),
        sa.Column('payment_gateway', sa.String(), nullable=False),
        sa.Column('payment_method', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('issuer_id', sa.String(), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.user_id'],
        ),
        sa.PrimaryKeyConstraint('customer_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
