"""add sku

Revision ID: 02e172ffd5ff
Revises: e90867cd08a1
Create Date: 2023-07-09 16:14:24.452599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e172ffd5ff'
down_revision = 'e90867cd08a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
