"""Refactor Settings table

Revision ID: 0b293b9fe558
Revises: bd627bd89eed
Create Date: 2024-09-26 14:03:31.940520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b293b9fe558'
down_revision: Union[str, None] = 'bd627bd89eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('locale', sa.String(), nullable=False))
    op.add_column('settings', sa.Column('provider', sa.String(), nullable=False))
    op.add_column('settings', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.alter_column('settings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('settings', 'settings_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('settings_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('settings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('settings', 'is_default')
    op.drop_column('settings', 'provider')
    op.drop_column('settings', 'locale')
    # ### end Alembic commands ###
