"""add column menu and showcase in category

Revision ID: 0df9bdfb7ade
Revises: ba74f3f57e5f
Create Date: 2023-09-09 07:12:32.161371
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df9bdfb7ade'
down_revision: Union[str, None] = 'ba74f3f57e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('menu', sa.Boolean(),server_default='0', nullable=False))
    op.add_column(
        'category', sa.Column('showcase', sa.Boolean(), server_default='0', nullable=False)
    )
    op.add_column(
        'order', sa.Column('affiliate_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'affiliate_id')
    op.drop_column('category', 'showcase')
    op.drop_column('category', 'menu')
    # ### end Alembic commands ###
