"""add column customer_id and user_id in order

Revision ID: 19215b4a119d
Revises: 67e50ec6d184
Create Date: 2023-09-09 10:07:10.098658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19215b4a119d'
down_revision: Union[str, None] = '67e50ec6d184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_customer_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(
        'order_customer_id_fkey', 'order', 'user', ['customer_id'], ['user_id']
    )
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
