"""add feature column in Product and image path in Category

Revision ID: 2b604a0e182a
Revises: 0258cb1bef06
Create Date: 2023-09-26 09:57:34.320359
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b604a0e182a'
down_revision: Union[str, None] = '0258cb1bef06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'category', sa.Column('image_path', sa.String(), nullable=True)
    )
    op.add_column(
        'product',
        sa.Column('feature', sa.Boolean(), server_default='0', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'feature')
    op.drop_column('category', 'image_path')
    # ### end Alembic commands ###
