"""empty message

Revision ID: 2c29e17bf5b3
Revises: 505773b1f8a5
Create Date: 2025-12-03 16:00:21.254950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c29e17bf5b3'
down_revision: Union[str, None] = '505773b1f8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_media_gallery',
    sa.Column('category_media_gallery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['uploaded_media.media_id'], ),
    sa.PrimaryKeyConstraint('category_media_gallery_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_media_gallery')
    # ### end Alembic commands ###
