"""empty message

Revision ID: 41a9792f4f3f
Revises: cf9fb307ec85
Create Date: 2023-12-19 20:09:54.349713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a9792f4f3f'
down_revision: Union[str, None] = 'cf9fb307ec85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('franchise')
    op.add_column(
        'sales_commission',
        sa.Column('release_data', sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_commission', 'release_data')
    op.create_table(
        'franchise',
        sa.Column(
            'franchise_id', sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            'communication_name',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'description', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'franshisee_name', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'franshisee_id', sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint('franchise_id', name='franchise_pkey'),
    )
    # ### end Alembic commands ###
