"""add payment_method table

Revision ID: 4d24e58ec8a1
Revises: f39ada3743cc
Create Date: 2023-08-11 10:44:47.963038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d24e58ec8a1'
down_revision: Union[str, None] = 'f39ada3743cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('payment_method', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_method')
    # ### end Alembic commands ###
