"""Add column terms in user table.

Revision ID: 57b325b40728
Revises: 1dba810f2de3
Create Date: 2025-01-30 21:43:30.855387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b325b40728'
down_revision: Union[str, None] = '1dba810f2de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms')
    # ### end Alembic commands ###
