"""Add new column in payment gateway

Revision ID: 58f19a55d4e7
Revises: 36ca18941bdf
Create Date: 2023-10-13 16:48:17.858315
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f19a55d4e7'
down_revision: Union[str, None] = '36ca18941bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payment',
        sa.Column(
            'gateway_payment_id',
            sa.Integer(),
            server_default='0',
            nullable=False,
        ),
    )
    op.drop_column('payment', 'gateway_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payment',
        sa.Column(
            'gateway_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('payment', 'gateway_payment_id')
    # ### end Alembic commands ###
