"""add column price and discount_price in order_items

Revision ID: 67e50ec6d184
Revises: 0df9bdfb7ade
Create Date: 2023-09-09 07:22:14.786347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e50ec6d184'
down_revision: Union[str, None] = '0df9bdfb7ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_items', sa.Column('price', sa.Numeric(), nullable=False)
    )
    op.add_column(
        'order_items',
        sa.Column('discount_price', sa.Numeric(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'discount_price')
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
