"""empty message.

Revision ID: 782f01e4d326
Revises: 6e08293f13fe
Create Date: 2023-07-05 18:55:34.078918
"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '782f01e4d326'
down_revision = '6e08293f13fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    # ### end Alembic commands ###
