"""empty message

Revision ID: a07e54b38b4e
Revises: 4bc709905973
Create Date: 2023-07-05 16:14:12.657703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07e54b38b4e'
down_revision = '4bc709905973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order', 'tracking_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('product', sa.Column('height', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('product', sa.Column('weight', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('product', sa.Column('diameter', sa.Numeric(precision=5, scale=3), nullable=True))
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product', 'showcase',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product', 'show_discount',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('product', 'quantity')
    op.drop_column('product', 'weigth')
    op.drop_column('product', 'heigth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('heigth', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('weigth', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('quantity', sa.INTEGER(), server_default=sa.text('9999'), autoincrement=False, nullable=True))
    op.alter_column('product', 'show_discount',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('product', 'showcase',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('product', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('product', 'diameter')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'height')
    op.alter_column('order', 'tracking_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('coupons')
    # ### end Alembic commands ###
