"""add column to cart uuid

Revision ID: b7184e6a261b
Revises: 30d0b083ec86
Create Date: 2023-09-07 08:58:11.616572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7184e6a261b'
down_revision: Union[str, None] = '30d0b083ec86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cart_uuid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cart_uuid')
    # ### end Alembic commands ###
