"""feat: add order_id in Payment table

Revision ID: c133a29dbf20
Revises: 37f3a4837831
Create Date: 2023-09-10 10:16:32.389419
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c133a29dbf20'
down_revision: Union[str, None] = '37f3a4837831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payment', sa.Column('order_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, 'payment', 'order', ['order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'order_id')
    # ### end Alembic commands ###
