"""add freight in order

Revision ID: ca38e148b72a
Revises: 8abcd682ce02
Create Date: 2023-11-22 14:53:30.965560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca38e148b72a'
down_revision: Union[str, None] = '8abcd682ce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('freight', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'freight')
    # ### end Alembic commands ###
