"""empty message

Revision ID: cf9fb307ec85
Revises: a7f1308444f7
Create Date: 2023-12-18 06:02:14.684234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf9fb307ec85'
down_revision: Union[str, None] = 'a7f1308444f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'coupons',
        sa.Column('commission_percentage', sa.Numeric(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'commission_percentage')
    # ### end Alembic commands ###
