"""feat: add order id in inventory

Revision ID: d6b16e0c27c0
Revises: c133a29dbf20
Create Date: 2023-09-10 11:11:48.867655
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b16e0c27c0'
down_revision: Union[str, None] = 'c133a29dbf20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'inventory', sa.Column('order_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, 'inventory', 'order', ['order_id'], ['order_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'order_id')
    # ### end Alembic commands ###
