"""change field from int to BIGINT

Revision ID: da6799c0cebe
Revises: dee9aad6041b
Create Date: 2024-02-28 13:07:39.612017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6799c0cebe'
down_revision: Union[str, None] = 'dee9aad6041b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_payment_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.alter_column(
        'payment',
        'gateway_payment_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        existing_server_default=sa.text('0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'payment',
        'gateway_payment_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text('0'),
    )
    op.add_column(
        'order',
        sa.Column(
            'payment_id', sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        'order_payment_id_fkey',
        'order',
        'payment',
        ['payment_id'],
        ['payment_id'],
    )
    # ### end Alembic commands ###
