"""empty message

Revision ID: dee9aad6041b
Revises: 41a9792f4f3f
Create Date: 2023-12-23 13:25:11.308627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee9aad6041b'
down_revision: Union[str, None] = '41a9792f4f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, 'order', 'coupons', ['coupon_id'], ['coupon_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'coupon_id')
    # ### end Alembic commands ###
