"""empty message

Revision ID: e90867cd08a1
Revises: 782f01e4d326
Create Date: 2023-07-09 16:11:31.187629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90867cd08a1'
down_revision = '782f01e4d326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sku', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sku')
    # ### end Alembic commands ###
