"""feat: add column affiliate in coupons

Revision ID: ee0f2b9481ba
Revises: d6b16e0c27c0
Create Date: 2023-09-14 06:45:58.623031
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0f2b9481ba'
down_revision: Union[str, None] = 'd6b16e0c27c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'coupons', sa.Column('affiliate_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, 'coupons', 'user', ['affiliate_id'], ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'affiliate_id')
    # ### end Alembic commands ###
