"""drop unused columns in Address

Revision ID: f39ada3743cc
Revises: 0e757a8d3e82
Create Date: 2023-08-10 10:08:45.751330
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39ada3743cc'
down_revision: Union[str, None] = '0e757a8d3e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'type_address')
    op.drop_column('address', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'address',
        sa.Column(
            'category', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'address',
        sa.Column(
            'type_address', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
