"""add column discount

Revision ID: fbf779e5ac80
Revises: b7184e6a261b
Create Date: 2023-09-07 09:14:04.008952
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf779e5ac80'
down_revision: Union[str, None] = 'b7184e6a261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('discount', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'discount')
    # ### end Alembic commands ###
