def test_create_credit_card_token_should_success(): ...


def test_create_invalid_credit_card_token_should_exception(): ...


def test_create_payment_should_success(): ...


def test_create_invalid_payment_should_exception(): ...


def create_pix_payment_should_success(): ...


def create_invalid_pix_payment_should_exception(): ...


def get_payment_should_success(): ...


def get_invalid_payment_should_exception(): ...


def cancell_payment_should_success(): ...


def cancell_invalid_payment_should_success(): ...
